name: covid19
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher:
  shared_preferences:
  http:
  dynamic_theme:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
     - family: Cabin
       fonts:
         - asset: fonts/Cabin-Bold.ttf
         - asset: fonts/Cabin-BoldItalic.ttf
         - asset: fonts/Cabin-Regular.ttf
         - asset: fonts/Cabin-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
